# Generated by Django 4.0.5 on 2022-07-27 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0014_pizza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mascota',
        ),
        migrations.AddField(
            model_name='pizza',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
