# Generated by Django 4.0.5 on 2022-07-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_delete_mascota_pizza_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='user',
        ),
    ]
