# Generated by Django 4.0.5 on 2022-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_pizza_avatar_alter_publisher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='avatar',
            field=models.ImageField(blank=True, default='silueta.jpg', null=True, upload_to='media/avatars'),
        ),
    ]
