# Generated by Django 4.0.5 on 2022-08-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_pizza_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='avatar',
            field=models.ImageField(blank=True, default='silueta.jpg', null=True, upload_to='avatars'),
        ),
    ]
